// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.search.indexserver.protobuf;

import com.google.common.primitives.Ints;
import com.search.indexserver.pojo.FieldAndDocId;

public final class InvertPro {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_TermInOneDoc_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_TermInOneDoc_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_TermInfo_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_TermInfo_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\tmsg.proto\"Y\n\014TermInOneDoc\022\r\n\005docId\030\001 \002" +
                        "(\005\022\r\n\005field\030\002 \002(\005\022\n\n\002tf\030\003 \001(\005\022\014\n\004rank\030\004 " +
                        "\001(\001\022\021\n\tpositions\030\005 \003(\005\"0\n\010TermInfo\022$\n\rte" +
                        "rmInDocList\030\001 \003(\0132\r.TermInOneDocB\'\n\032com." +
                        "search.engine.protobufB\tInvertPro"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_TermInOneDoc_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TermInOneDoc_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_TermInOneDoc_descriptor,
                new String[]{"DocId", "Field", "Tf", "Rank", "Positions",});
        internal_static_TermInfo_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_TermInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_TermInfo_descriptor,
                new String[]{"TermInDocList",});
    }

    private InvertPro() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface TermInOneDocOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TermInOneDoc)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 docId = 1;</code>
         */
        boolean hasDocId();

        /**
         * <code>required int32 docId = 1;</code>
         */
        int getDocId();

        /**
         * <code>required int32 field = 2;</code>
         */
        boolean hasField();

        /**
         * <code>required int32 field = 2;</code>
         */
        int getField();

        /**
         * <code>optional int32 tf = 3;</code>
         */
        boolean hasTf();

        /**
         * <code>optional int32 tf = 3;</code>
         */
        int getTf();

        /**
         * <code>optional double rank = 4;</code>
         */
        boolean hasRank();

        /**
         * <code>optional double rank = 4;</code>
         */
        double getRank();

        /**
         * <code>repeated int32 positions = 5;</code>
         */
        java.util.List<Integer> getPositionsList();

        /**
         * <code>repeated int32 positions = 5;</code>
         */
        int getPositionsCount();

        /**
         * <code>repeated int32 positions = 5;</code>
         */
        int getPositions(int index);
    }

    public interface TermInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TermInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        java.util.List<com.search.indexserver.protobuf.InvertPro.TermInOneDoc>
        getTermInDocListList();

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        com.search.indexserver.protobuf.InvertPro.TermInOneDoc getTermInDocList(int index);

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        int getTermInDocListCount();

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        java.util.List<? extends com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder>
        getTermInDocListOrBuilderList();

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder getTermInDocListOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code TermInOneDoc}
     */
    public static final class TermInOneDoc extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:TermInOneDoc)
            TermInOneDocOrBuilder, Comparable<Object> {
        public static final int DOCID_FIELD_NUMBER = 1;
        public static final int FIELD_FIELD_NUMBER = 2;
        public static final int TF_FIELD_NUMBER = 3;
        public static final int RANK_FIELD_NUMBER = 4;
        public static final int POSITIONS_FIELD_NUMBER = 5;
        @Deprecated
        public static final com.google.protobuf.Parser<TermInOneDoc>
                PARSER = new com.google.protobuf.AbstractParser<TermInOneDoc>() {
            public TermInOneDoc parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                try {
                    return new TermInOneDoc(input, extensionRegistry);
                } catch (RuntimeException e) {
                    if (e.getCause() instanceof
                            com.google.protobuf.InvalidProtocolBufferException) {
                        throw (com.google.protobuf.InvalidProtocolBufferException)
                                e.getCause();
                    }
                    throw e;
                }
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:TermInOneDoc)
        private static final com.search.indexserver.protobuf.InvertPro.TermInOneDoc DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.search.indexserver.protobuf.InvertPro.TermInOneDoc();
        }

        private int bitField0_;
        private int docId_;
        private int field_;
        private int tf_;
        private double rank_;
        private java.util.List<Integer> positions_;
        private byte memoizedIsInitialized = -1;

        // Use TermInOneDoc.newBuilder() to construct.
        private TermInOneDoc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private TermInOneDoc() {
            docId_ = 0;
            field_ = 0;
            tf_ = 0;
            rank_ = 0D;
            positions_ = java.util.Collections.emptyList();
        }

        private TermInOneDoc(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            docId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            field_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            tf_ = input.readInt32();
                            break;
                        }
                        case 33: {
                            bitField0_ |= 0x00000008;
                            rank_ = input.readDouble();
                            break;
                        }
                        case 40: {
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                                positions_ = new java.util.ArrayList<Integer>();
                                mutable_bitField0_ |= 0x00000010;
                            }
                            positions_.add(input.readInt32());
                            break;
                        }
                        case 42: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                                positions_ = new java.util.ArrayList<Integer>();
                                mutable_bitField0_ |= 0x00000010;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                positions_.add(input.readInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                    positions_ = java.util.Collections.unmodifiableList(positions_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.search.indexserver.protobuf.InvertPro.internal_static_TermInOneDoc_descriptor;
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.search.indexserver.protobuf.InvertPro.TermInOneDoc prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInOneDoc getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<TermInOneDoc> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.search.indexserver.protobuf.InvertPro.internal_static_TermInOneDoc_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.search.indexserver.protobuf.InvertPro.TermInOneDoc.class, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder.class);
        }

        /**
         * <code>required int32 docId = 1;</code>
         */
        public boolean hasDocId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 docId = 1;</code>
         */
        public int getDocId() {
            return docId_;
        }

        /**
         * <code>required int32 field = 2;</code>
         */
        public boolean hasField() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int32 field = 2;</code>
         */
        public int getField() {
            return field_;
        }

        /**
         * <code>optional int32 tf = 3;</code>
         */
        public boolean hasTf() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional int32 tf = 3;</code>
         */
        public int getTf() {
            return tf_;
        }

        /**
         * <code>optional double rank = 4;</code>
         */
        public boolean hasRank() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional double rank = 4;</code>
         */
        public double getRank() {
            return rank_;
        }

        /**
         * <code>repeated int32 positions = 5;</code>
         */
        public java.util.List<Integer>
        getPositionsList() {
            return positions_;
        }

        /**
         * <code>repeated int32 positions = 5;</code>
         */
        public int getPositionsCount() {
            return positions_.size();
        }

        /**
         * <code>repeated int32 positions = 5;</code>
         */
        public int getPositions(int index) {
            return positions_.get(index);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasDocId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasField()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, docId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, field_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, tf_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeDouble(4, rank_);
            }
            for (int i = 0; i < positions_.size(); i++) {
                output.writeInt32(5, positions_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, docId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, field_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, tf_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(4, rank_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < positions_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(positions_.get(i));
                }
                size += dataSize;
                size += 1 * getPositionsList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public int compareTo(Object o) {
            if (o instanceof Integer) {
                return Integer.compare(getDocId(), (Integer) o);
            } else if (o instanceof FieldAndDocId) {
                int res = Ints.compare(getField(), ((FieldAndDocId) o).getFieldId());
                return res != 0 ? res : Ints.compare(getDocId(), ((FieldAndDocId) o).getDocId());
            }
            return 0;
        }

        @Override
        public com.google.protobuf.Parser<TermInOneDoc> getParserForType() {
            return PARSER;
        }

        public com.search.indexserver.protobuf.InvertPro.TermInOneDoc getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code TermInOneDoc}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TermInOneDoc)
                com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder {
            private int bitField0_;
            private int docId_;
            private int field_;
            private int tf_;
            private double rank_;
            private java.util.List<Integer> positions_ = java.util.Collections.emptyList();

            // Construct using com.search.engine.protobuf.InvertPro.TermInOneDoc.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.search.indexserver.protobuf.InvertPro.internal_static_TermInOneDoc_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.search.indexserver.protobuf.InvertPro.internal_static_TermInOneDoc_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.search.indexserver.protobuf.InvertPro.TermInOneDoc.class, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                docId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                field_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                tf_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                rank_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000008);
                positions_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.search.indexserver.protobuf.InvertPro.internal_static_TermInOneDoc_descriptor;
            }

            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc getDefaultInstanceForType() {
                return com.search.indexserver.protobuf.InvertPro.TermInOneDoc.getDefaultInstance();
            }

            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc build() {
                com.search.indexserver.protobuf.InvertPro.TermInOneDoc result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc buildPartial() {
                com.search.indexserver.protobuf.InvertPro.TermInOneDoc result = new com.search.indexserver.protobuf.InvertPro.TermInOneDoc(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.docId_ = docId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.field_ = field_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.tf_ = tf_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.rank_ = rank_;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    positions_ = java.util.Collections.unmodifiableList(positions_);
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.positions_ = positions_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.search.indexserver.protobuf.InvertPro.TermInOneDoc) {
                    return mergeFrom((com.search.indexserver.protobuf.InvertPro.TermInOneDoc) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.search.indexserver.protobuf.InvertPro.TermInOneDoc other) {
                if (other == com.search.indexserver.protobuf.InvertPro.TermInOneDoc.getDefaultInstance()) return this;
                if (other.hasDocId()) {
                    setDocId(other.getDocId());
                }
                if (other.hasField()) {
                    setField(other.getField());
                }
                if (other.hasTf()) {
                    setTf(other.getTf());
                }
                if (other.hasRank()) {
                    setRank(other.getRank());
                }
                if (!other.positions_.isEmpty()) {
                    if (positions_.isEmpty()) {
                        positions_ = other.positions_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensurePositionsIsMutable();
                        positions_.addAll(other.positions_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasDocId()) {
                    return false;
                }
                if (!hasField()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.search.indexserver.protobuf.InvertPro.TermInOneDoc parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.search.indexserver.protobuf.InvertPro.TermInOneDoc) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int32 docId = 1;</code>
             */
            public boolean hasDocId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 docId = 1;</code>
             */
            public int getDocId() {
                return docId_;
            }

            /**
             * <code>required int32 docId = 1;</code>
             */
            public Builder setDocId(int value) {
                bitField0_ |= 0x00000001;
                docId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 docId = 1;</code>
             */
            public Builder clearDocId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                docId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 field = 2;</code>
             */
            public boolean hasField() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int32 field = 2;</code>
             */
            public int getField() {
                return field_;
            }

            /**
             * <code>required int32 field = 2;</code>
             */
            public Builder setField(int value) {
                bitField0_ |= 0x00000002;
                field_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 field = 2;</code>
             */
            public Builder clearField() {
                bitField0_ = (bitField0_ & ~0x00000002);
                field_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 tf = 3;</code>
             */
            public boolean hasTf() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional int32 tf = 3;</code>
             */
            public int getTf() {
                return tf_;
            }

            /**
             * <code>optional int32 tf = 3;</code>
             */
            public Builder setTf(int value) {
                bitField0_ |= 0x00000004;
                tf_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 tf = 3;</code>
             */
            public Builder clearTf() {
                bitField0_ = (bitField0_ & ~0x00000004);
                tf_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional double rank = 4;</code>
             */
            public boolean hasRank() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional double rank = 4;</code>
             */
            public double getRank() {
                return rank_;
            }

            /**
             * <code>optional double rank = 4;</code>
             */
            public Builder setRank(double value) {
                bitField0_ |= 0x00000008;
                rank_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional double rank = 4;</code>
             */
            public Builder clearRank() {
                bitField0_ = (bitField0_ & ~0x00000008);
                rank_ = 0D;
                onChanged();
                return this;
            }

            private void ensurePositionsIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    positions_ = new java.util.ArrayList<Integer>(positions_);
                    bitField0_ |= 0x00000010;
                }
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public java.util.List<Integer>
            getPositionsList() {
                return java.util.Collections.unmodifiableList(positions_);
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public int getPositionsCount() {
                return positions_.size();
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public int getPositions(int index) {
                return positions_.get(index);
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public Builder setPositions(
                    int index, int value) {
                ensurePositionsIsMutable();
                positions_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public Builder addPositions(int value) {
                ensurePositionsIsMutable();
                positions_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public Builder addAllPositions(
                    Iterable<? extends Integer> values) {
                ensurePositionsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, positions_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 positions = 5;</code>
             */
            public Builder clearPositions() {
                positions_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:TermInOneDoc)
        }

    }

    /**
     * Protobuf type {@code TermInfo}
     */
    public static final class TermInfo extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:TermInfo)
            TermInfoOrBuilder {
        public static final int TERMINDOCLIST_FIELD_NUMBER = 1;
        @Deprecated
        public static final com.google.protobuf.Parser<TermInfo>
                PARSER = new com.google.protobuf.AbstractParser<TermInfo>() {
            public TermInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                try {
                    return new TermInfo(input, extensionRegistry);
                } catch (RuntimeException e) {
                    if (e.getCause() instanceof
                            com.google.protobuf.InvalidProtocolBufferException) {
                        throw (com.google.protobuf.InvalidProtocolBufferException)
                                e.getCause();
                    }
                    throw e;
                }
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:TermInfo)
        private static final com.search.indexserver.protobuf.InvertPro.TermInfo DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.search.indexserver.protobuf.InvertPro.TermInfo();
        }

        private java.util.List<com.search.indexserver.protobuf.InvertPro.TermInOneDoc> termInDocList_;
        private byte memoizedIsInitialized = -1;

        // Use TermInfo.newBuilder() to construct.
        private TermInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private TermInfo() {
            termInDocList_ = java.util.Collections.emptyList();
        }

        private TermInfo(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                termInDocList_ = new java.util.ArrayList<com.search.indexserver.protobuf.InvertPro.TermInOneDoc>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            termInDocList_.add(input.readMessage(com.search.indexserver.protobuf.InvertPro.TermInOneDoc.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    termInDocList_ = java.util.Collections.unmodifiableList(termInDocList_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.search.indexserver.protobuf.InvertPro.internal_static_TermInfo_descriptor;
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.search.indexserver.protobuf.InvertPro.TermInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.search.indexserver.protobuf.InvertPro.TermInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<TermInfo> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.search.indexserver.protobuf.InvertPro.internal_static_TermInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.search.indexserver.protobuf.InvertPro.TermInfo.class, com.search.indexserver.protobuf.InvertPro.TermInfo.Builder.class);
        }

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        public java.util.List<com.search.indexserver.protobuf.InvertPro.TermInOneDoc> getTermInDocListList() {
            return termInDocList_;
        }

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        public java.util.List<? extends com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder>
        getTermInDocListOrBuilderList() {
            return termInDocList_;
        }

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        public int getTermInDocListCount() {
            return termInDocList_.size();
        }

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        public com.search.indexserver.protobuf.InvertPro.TermInOneDoc getTermInDocList(int index) {
            return termInDocList_.get(index);
        }

        /**
         * <code>repeated .TermInOneDoc termInDocList = 1;</code>
         */
        public com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder getTermInDocListOrBuilder(
                int index) {
            return termInDocList_.get(index);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            for (int i = 0; i < getTermInDocListCount(); i++) {
                if (!getTermInDocList(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < termInDocList_.size(); i++) {
                output.writeMessage(1, termInDocList_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < termInDocList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, termInDocList_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<TermInfo> getParserForType() {
            return PARSER;
        }

        public com.search.indexserver.protobuf.InvertPro.TermInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code TermInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TermInfo)
                com.search.indexserver.protobuf.InvertPro.TermInfoOrBuilder {
            private int bitField0_;
            private java.util.List<com.search.indexserver.protobuf.InvertPro.TermInOneDoc> termInDocList_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilder<
                    com.search.indexserver.protobuf.InvertPro.TermInOneDoc, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder, com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder> termInDocListBuilder_;

            // Construct using com.search.engine.protobuf.InvertPro.TermInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.search.indexserver.protobuf.InvertPro.internal_static_TermInfo_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.search.indexserver.protobuf.InvertPro.internal_static_TermInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.search.indexserver.protobuf.InvertPro.TermInfo.class, com.search.indexserver.protobuf.InvertPro.TermInfo.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getTermInDocListFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                if (termInDocListBuilder_ == null) {
                    termInDocList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    termInDocListBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.search.indexserver.protobuf.InvertPro.internal_static_TermInfo_descriptor;
            }

            public com.search.indexserver.protobuf.InvertPro.TermInfo getDefaultInstanceForType() {
                return com.search.indexserver.protobuf.InvertPro.TermInfo.getDefaultInstance();
            }

            public com.search.indexserver.protobuf.InvertPro.TermInfo build() {
                com.search.indexserver.protobuf.InvertPro.TermInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.search.indexserver.protobuf.InvertPro.TermInfo buildPartial() {
                com.search.indexserver.protobuf.InvertPro.TermInfo result = new com.search.indexserver.protobuf.InvertPro.TermInfo(this);
                int from_bitField0_ = bitField0_;
                if (termInDocListBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        termInDocList_ = java.util.Collections.unmodifiableList(termInDocList_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.termInDocList_ = termInDocList_;
                } else {
                    result.termInDocList_ = termInDocListBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.search.indexserver.protobuf.InvertPro.TermInfo) {
                    return mergeFrom((com.search.indexserver.protobuf.InvertPro.TermInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.search.indexserver.protobuf.InvertPro.TermInfo other) {
                if (other == com.search.indexserver.protobuf.InvertPro.TermInfo.getDefaultInstance()) return this;
                if (termInDocListBuilder_ == null) {
                    if (!other.termInDocList_.isEmpty()) {
                        if (termInDocList_.isEmpty()) {
                            termInDocList_ = other.termInDocList_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureTermInDocListIsMutable();
                            termInDocList_.addAll(other.termInDocList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.termInDocList_.isEmpty()) {
                        if (termInDocListBuilder_.isEmpty()) {
                            termInDocListBuilder_.dispose();
                            termInDocListBuilder_ = null;
                            termInDocList_ = other.termInDocList_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            termInDocListBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getTermInDocListFieldBuilder() : null;
                        } else {
                            termInDocListBuilder_.addAllMessages(other.termInDocList_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                for (int i = 0; i < getTermInDocListCount(); i++) {
                    if (!getTermInDocList(i).isInitialized()) {
                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.search.indexserver.protobuf.InvertPro.TermInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.search.indexserver.protobuf.InvertPro.TermInfo) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureTermInDocListIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    termInDocList_ = new java.util.ArrayList<com.search.indexserver.protobuf.InvertPro.TermInOneDoc>(termInDocList_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public java.util.List<com.search.indexserver.protobuf.InvertPro.TermInOneDoc> getTermInDocListList() {
                if (termInDocListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(termInDocList_);
                } else {
                    return termInDocListBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public int getTermInDocListCount() {
                if (termInDocListBuilder_ == null) {
                    return termInDocList_.size();
                } else {
                    return termInDocListBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc getTermInDocList(int index) {
                if (termInDocListBuilder_ == null) {
                    return termInDocList_.get(index);
                } else {
                    return termInDocListBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder setTermInDocList(
                    int index, com.search.indexserver.protobuf.InvertPro.TermInOneDoc value) {
                if (termInDocListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTermInDocListIsMutable();
                    termInDocList_.set(index, value);
                    onChanged();
                } else {
                    termInDocListBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder setTermInDocList(
                    int index, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder builderForValue) {
                if (termInDocListBuilder_ == null) {
                    ensureTermInDocListIsMutable();
                    termInDocList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    termInDocListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder addTermInDocList(com.search.indexserver.protobuf.InvertPro.TermInOneDoc value) {
                if (termInDocListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTermInDocListIsMutable();
                    termInDocList_.add(value);
                    onChanged();
                } else {
                    termInDocListBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder addTermInDocList(
                    int index, com.search.indexserver.protobuf.InvertPro.TermInOneDoc value) {
                if (termInDocListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureTermInDocListIsMutable();
                    termInDocList_.add(index, value);
                    onChanged();
                } else {
                    termInDocListBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder addTermInDocList(
                    com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder builderForValue) {
                if (termInDocListBuilder_ == null) {
                    ensureTermInDocListIsMutable();
                    termInDocList_.add(builderForValue.build());
                    onChanged();
                } else {
                    termInDocListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder addTermInDocList(
                    int index, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder builderForValue) {
                if (termInDocListBuilder_ == null) {
                    ensureTermInDocListIsMutable();
                    termInDocList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    termInDocListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder addAllTermInDocList(
                    Iterable<? extends com.search.indexserver.protobuf.InvertPro.TermInOneDoc> values) {
                if (termInDocListBuilder_ == null) {
                    ensureTermInDocListIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, termInDocList_);
                    onChanged();
                } else {
                    termInDocListBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder clearTermInDocList() {
                if (termInDocListBuilder_ == null) {
                    termInDocList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    termInDocListBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public Builder removeTermInDocList(int index) {
                if (termInDocListBuilder_ == null) {
                    ensureTermInDocListIsMutable();
                    termInDocList_.remove(index);
                    onChanged();
                } else {
                    termInDocListBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder getTermInDocListBuilder(
                    int index) {
                return getTermInDocListFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder getTermInDocListOrBuilder(
                    int index) {
                if (termInDocListBuilder_ == null) {
                    return termInDocList_.get(index);
                } else {
                    return termInDocListBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public java.util.List<? extends com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder>
            getTermInDocListOrBuilderList() {
                if (termInDocListBuilder_ != null) {
                    return termInDocListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(termInDocList_);
                }
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder addTermInDocListBuilder() {
                return getTermInDocListFieldBuilder().addBuilder(
                        com.search.indexserver.protobuf.InvertPro.TermInOneDoc.getDefaultInstance());
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder addTermInDocListBuilder(
                    int index) {
                return getTermInDocListFieldBuilder().addBuilder(
                        index, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.getDefaultInstance());
            }

            /**
             * <code>repeated .TermInOneDoc termInDocList = 1;</code>
             */
            public java.util.List<com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder>
            getTermInDocListBuilderList() {
                return getTermInDocListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.search.indexserver.protobuf.InvertPro.TermInOneDoc, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder, com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder>
            getTermInDocListFieldBuilder() {
                if (termInDocListBuilder_ == null) {
                    termInDocListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.search.indexserver.protobuf.InvertPro.TermInOneDoc, com.search.indexserver.protobuf.InvertPro.TermInOneDoc.Builder, com.search.indexserver.protobuf.InvertPro.TermInOneDocOrBuilder>(
                            termInDocList_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    termInDocList_ = null;
                }
                return termInDocListBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:TermInfo)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
